### ISSUE TITLE
Items crearted from branches on core database looses layout on sync

### ISSUE THREAD

**Issue by mortenengel** [SitecoreUnicorn/Unicorn#318]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Creating an item from a master on the core database and then adding a layout to it, serializes nicely. But when you want to sync this to another instance, the layout is gone.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Add a predicate to include core:/sitecore/content/Applications/test
2. Load Content Editor for core database
3. Navigate to /sitecore/content/Applications
4. Right click the node in the tree, and insert a new application
5. Go to layout details and choose any layout
6. Backup the serialized test item (copy/paste)
7. Delete the test item in Sitecore
8. Reinstate the backup
9. Run a Unicorn sync
10. You have the item again, but the layout is gone. 

This seems to happen anywhere on the core database, from any item that is created from the masters under core:/sitecore/masters. I have done a workaround and just created my template directly from the template rather than from the branch - or simply by removing the following line from the .yml before syncing: 
BranchID: "1f0770ea-8b77-4110-91aa-cc00dee102dd"

**What is the expected behavior?**
Having the item, but with the layout.

**Please mention your Sitecore version and Unicorn version.**
Tested on Sitecore 8.2 and 9.0, Unicorn 4.0.3

Took me a while to find the exact cause of this bug, unfortunately I don't have time to find a code solution right now, but if you'd like me to, let me know and I'll figure it out when I have more time.

**Comment by cassidydotdk** [comment]
@mortenengel Please try this on Unicorn 4.0.4. 4.0.3 had a number of problems related to language fallback and enforced version presence, that could be the root cause of this. If the problem is confirmed to exist on 4.0.4, I will open an investigation.

**Comment by mortenengel** [comment]
Just tested, The bug still happens in Unicorn 4.0.4

**Comment by cassidydotdk** [comment]
Aight, thanks :-)  Will dig into it.

**Comment by cassidydotdk** [comment]
Confirmed.  The following YAML does indeed re-create the item, with blank presentation details.

```

---
ID: "332b4c61-42b6-4036-97c7-69ef1b841ff8"
Parent: "c74ac643-53c8-4f1e-9508-840cdc72aaca"
Template: "eb06cec0-5e2d-4dc4-875b-01adcc577d13"
Path: /sitecore/content/Applications/test
DB: core
BranchID: "1f0770ea-8b77-4110-91aa-cc00dee102dd"
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: /sitecore/shell/themes/standard/Software/16x16/application.png
- ID: "094829c2-d7a7-4c38-b025-b99ff2001b56"
  Hint: Disable close
  Type: checkbox
  Value: 0
- ID: "2b3ecbbc-432a-4cea-bb75-ce481b644ff8"
  Hint: Disable resize
  Type: checkbox
  Value: 0
- ID: "b4e951ee-906f-4249-b2c6-68e31c82e118"
  Hint: Disable maximize
  Type: checkbox
  Value: 0
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 0
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{2C248BB8-6521-4147-AD49-46463AA768BA}" />
    </r>
- ID: "f54c1557-f8ce-4130-90a7-b89575c4cdbe"
  Hint: Disable minimize
  Type: checkbox
  Value: 0
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{35517498-AD36-493A-B91B-2C3D4D375B37}"
- ID: "fc2b18b3-1631-4c3f-9e47-51df05030026"
  Hint: Icon
  Value: Software/32x32/application.png
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181120T142119Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "67b6378b-c9f1-47c7-9cac-bfa79b0727d9"
      Hint: Display name
      Value: test

```
