### ISSUE TITLE
Unable to update shared checkbox field from standard value

### ISSUE THREAD

**Issue by JeffDarchuk** [SitecoreUnicorn/Unicorn#319]
SC 9.0.1

Unicorn 4.0.4

To reproduce this error:

1. Create a new template with a checkbox field marked shared
2. Create a standard values item for this template and set this checkbox to checked
3. Create an item that's tracked in unicorn that uses this template
4. Uncheck the checkbox in the particular instance of the item
5. Add and commit it to GIT (you'll see the yml has the field change)
6. Use field reset to reset the unchecked box back to the standard value of checked
7. Do a git reset --hard to remove the yml file change
8. Unicorn sync and see that the item is still using standard values despite the yml directing it to uncheck the checkbox
9. Delete the item entirely
10. Do another git reset --hard to bring back the yml file
11. Run another unicorn sync and see that the item is properly brought back with the checkbox unchecked instead of the standard value as we would expect

**Comment by cassidydotdk** [comment]
I've found a way to reliably reproduce this. At least I am 90% sure it's the same issue. The Rainbow ItemComparer will not properly detect the difference between an unchecked checkbox and a null value and therefore not realise that the field value needs to be reset. 

Working on a fix.

**Comment by cassidydotdk** [comment]
I believe this to be fixed in this release of Rainbow.

https://github.com/SitecoreUnicorn/Rainbow/releases/tag/2.0.6-pre1

If you could take it for a spin @JeffDarchuk to confirm, that would be great. I have it working locally, and it also does the job on a client solution I'm currently working.

**Comment by JeffDarchuk** [comment]
![image](https://user-images.githubusercontent.com/12616331/51262910-220bc280-1968-11e9-8e9e-13389e6578fb.png)
unfortunately it appears to still be happening for me

**Comment by cassidydotdk** [comment]
Yes. Pesky little bugger, this problem ;-)

Anyway it has now been narrowed down. The fix from 2.0.6-pre1 solves the root issue, but is being partially nullified by the code in the CheckboxComparer/CheckboxFieldFormatter code. Will post an update when I have it.

**Comment by cassidydotdk** [comment]
@JeffDarchuk Leaving the Checkbox field configuration is a workaround, but I believe I've now identified the root cause. Rainbow no longer internally attempts to compare two `null` values (for Checkbox fields or otherwise) and will assume them to be identical. This means it will no longer (in your specific case) no longer call the CheckboxFieldFormatter and falsely return `0` which will cause your field to NOT be reset to standard value correctly.

Mind checking out https://github.com/SitecoreUnicorn/Rainbow/releases/tag/2.0.6-pre3 and confirm this solves it for you?

**Comment by JeffDarchuk** [comment]
Hey Mark, unfortunately after updating to 2.0.6-pre3 the problem still persists.  Sorry it took me so long, had a long chain of high intensity production issues i had to take care of.

**Comment by cassidydotdk** [comment]
That's alright :-)   I just hoped the fix would bypass the code we know to be at fault; given @kamsar's insistence of the code's utmost importance to balance in the world ;-)

I'll take it out.

**Comment by cassidydotdk** [comment]
So the root cause is here. Once reset, this is the resulting YML.

```
---
ID: "ca261ec6-8471-4949-8aca-6a689ef24306"
Parent: "dad86df8-94ad-46d6-a438-bf301e7ac7fe"
Template: "5fcb7984-7dc6-465d-b08c-275f9edffe42"
Path: /sitecore/content/Home/Test/Test Checkbox Item
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190320T104000Z
```

And the version with the checkbox explicitly unchecked

```
---
ID: "ca261ec6-8471-4949-8aca-6a689ef24306"
Parent: "dad86df8-94ad-46d6-a438-bf301e7ac7fe"
Template: "5fcb7984-7dc6-465d-b08c-275f9edffe42"
Path: /sitecore/content/Home/Test/Test Checkbox Item
DB: master
SharedFields:
- ID: "c761633a-49d1-4a5c-b998-3d9202732ea2"
  Hint: Test Checkbox Field
  Type: Checkbox
  Value: 0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190320T104000Z
```

Basically, since the field is (correctly) not present in the version of the item with only a Standard Values value, the Checkbox field gets ignored. Normally, the DefaultDeserializer (in PasteSharedFields) would ensure that the field value gets reset as expected under these circumstances, but (I suspect) the CheckboxComparison code gets in the way of that. This is why commenting out this field comparer entirely will revert Rainbow back to default behaviour and thus work correctly.

**Comment by cassidydotdk** [comment]
I expanded the test parameters. I added a regular text field to the mix, gave it a standard value. Then I blanked it on the item, resulting in this YML.

```
---
ID: "ca261ec6-8471-4949-8aca-6a689ef24306"
Parent: "dad86df8-94ad-46d6-a438-bf301e7ac7fe"
Template: "5fcb7984-7dc6-465d-b08c-275f9edffe42"
Path: /sitecore/content/Home/Test/Test Checkbox Item
DB: master
SharedFields:
- ID: "92470610-76f1-48f5-95dc-8566cc4586d6"
  Hint: Test Text Field
  Value: 
- ID: "c761633a-49d1-4a5c-b998-3d9202732ea2"
  Hint: Test Checkbox Field
  Type: Checkbox
  Value: 0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190320T104000Z
```

Repeating the steps above, the field value does NOT get reset. Not just for the checkbox, but also the text field. I am now positive I have the root cause.
