### ISSUE TITLE
Exception in ReportStatus method used by PowerShell

### ISSUE THREAD

**Issue by michaellwest** [SitecoreUnicorn/Unicorn#394]
Detected a bug while running the following script:

```powershell
# Step 0
Get-Item -Path "master:\content\home\item1" -ErrorAction 0 | Remove-Item
Get-Item -Path "master:\content\home\item2" -ErrorAction 0 | Remove-Item

# Step 1
$homeItem = Get-Item -Path "master:" -ID "{110D559F-DEA5-42EA-9C1C-8A5DF7E70EF9}"
New-Item -Parent $homeItem -Name "Item1" -ItemType "{76036F5E-CBCE-46D1-AF0A-4143F9B557AA}"
New-Item -Parent $homeItem -Name "Item2" -ItemType "{76036F5E-CBCE-46D1-AF0A-4143F9B557AA}"

# Step 2
$item2 = Get-Item -Path "master:\content\home\item2"
$rainbowYaml = ConvertTo-RainbowYaml -Item $item2

# Step 3
$item1 = Get-Item -Path "master:\content\home\item1"
$item2 | Move-Item -DestinationItem $item1
$item2.Title = "Item2 Moved"

# Step 4
$rainbowItem = ConvertFrom-RainbowYaml -Yaml $rainbowYaml
Import-RainbowItem -Item $rainbowItem
```

> /sitecore/content/Home/Item2
> Import-RainbowItem : Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
> At line:5 char:1
> + Import-RainbowItem -Item $rainbowItem
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Import-RainbowItem], FormatException
>     + FullyQualifiedErrorId : System.FormatException,Unicorn.PowerShell.ImportRainbowYamlCommand

Turns out that the method `Unicorn.PowerShell.PowershellProgressStatus.ReportStatus` encounters a scenario where the format parameters are empty on line 43.

Potential fix:
```csharp
var message = formatParameters.Length == 0 ? statusMessage : string.Format(statusMessage, formatParameters);
```

Outcome of change:

```text
Name                             Children Language Version Id                                     TemplateName
----                             -------- -------- ------- --                                     ------------
Item1                            False    en       1       {05FDB056-A7E7-42C7-9C84-57C21935F5C8} Sample Item
Item2                            False    en       1       {2B2EEF34-5196-4169-ADF8-5E3473384CFE} Sample Item
/sitecore/content/Home/Item2
* [M] from {05FDB056-A7E7-42C7-9C84-57C21935F5C8} to {110D559F-DEA5-42EA-9C1C-8A5DF7E70EF9}
* [U] en#1: Title
```

**Comment by michaellwest** [comment]
Sample yaml:

```
---
ID: "e73b4e5b-4d6d-44a0-98e7-ed25438c0e9f"
Parent: "110d559f-dea5-42ea-9c1c-8a5df7e70ef9"
Template: "76036f5e-cbce-46d1-af0a-4143f9b557aa"
Path: /sitecore/content/Home/Item2
DB: master
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{A5BC37E7-ED96-4C1E-8590-A26E64DB55EA}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200914T124030Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{190B1C84-F1BE-47ED-AA41-F42193D9C8FC}"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "75577384-3c97-45da-a847-81b00500e250"
      Hint: Title
      Value: Item2
```
